### ISSUE TITLE
Commit naming

### ISSUE THREAD

**Issue by v-bondarenko364** [radekxrandom/device_bridge#11]
You latest commit have just - `redne`

It's very important to have clear commit names.
Consider to write commit names according to convetional commint specification:
https://www.conventionalcommits.org/en/v1.0.0/

If you use this specification your naming would be much more cleaner.

So your commit name could be: `chore(docs): update readme`

It means that:
- it's ordinary code supporting (because of `chore` tag)
- it's covers docs "module" in your application

**Comment by radekxrandom** [comment]
Here you got a point, this is something I stopped doing later.
