### ISSUE TITLE
Folder organisation (front)

### ISSUE THREAD

**Issue by v-bondarenko364** [radekxrandom/device_bridge#12]
In this project, it's normally to have modules right inside you `src/` folder

But in larger projects better to use something like project structure:

src/
    App.jsx
    yarn.lock
    package.json
    ...
    modules/
        components/ <-- common components
        connected/
        disconnected/
    helpers/
    mockData/

**Comment by radekxrandom** [comment]
"But **in larger projects better** to use something like project structure:" should be the point here. Go take a look at my bigger projects.
