### ISSUE TITLE
Styles

### ISSUE THREAD

**Issue by v-bondarenko364** [radekxrandom/device_bridge#2]
Instead of using `App.css` file (or other styling files) you could use [styled-components](https://styled-components.com/) package. 

This package allows you to create Styled components that are more reusable and could be imported.
After your react component you could create styled-components e.g:
`
export const Sidebar = styled.div`
   width: 100px;
   background-color: red;
`;
`;

And then you could use is it `<Sidebar>`
`
_** This component could be imported by others files._

**Comment by radekxrandom** [comment]
Yeah I know. Nothing beats CSS when it comes to the performance now, does it? I thought you cared about that.
