### ISSUE TITLE
Import order

### ISSUE THREAD

**Issue by v-bondarenko364** [radekxrandom/device_bridge#3]
https://github.com/radekxrandom/device_bridge/blob/95b810411554fce0a641294c193e3faeba369f21/front/src/App.js#L3

Another point of improving your code styling is - import ordering.

I prefer using import grouping with import sorting.

1. Import grouping:
I group import by 3 group
- third party packages (`import _ from 'lodash'`)
- import from other modules (e.g: `import {some} from 'app/reducers/app.reducer.ts';`)
- import from same module (e.g: `import Component from './Test.tsx' or import Component from '../Text.tsx'` but not 'import Test from '../../../Text.tsx' in such case better to use import from module like import `import Test from modules/test/Test.tsx`)

2. Import sorting
In each import group I sort packages alphabetically by their path (omit symbols and register)

So after some refactoring you get something like this:

```import React from "react";
import {
	isMobile,
	browserName,
	mobileModel,
	osName
} from "react-device-detect";
import QRCode from "react-qr-code";

import "./App.css";
import QrComponent from "./components/QrComponent";
import ConnectedViewContainer from "./connected/ConnectedViewContainer";
import DisconnectedViewContainer from "./disconnected/DisconnectedViewContainer";
import { mockSharedFiles, mockConnectedDevices } from "./mockData/mockLists";
import { socket } from "./socket";```

**Comment by radekxrandom** [comment]
Yeah, I got an extension that sorts my imports because it was kinda messy beforehand.
