### ISSUE TITLE
Helpers

### ISSUE THREAD

**Issue by v-bondarenko364** [radekxrandom/device_bridge#4]
https://github.com/radekxrandom/device_bridge/blob/95b810411554fce0a641294c193e3faeba369f21/front/src/App.js#L16

Such functions could be placed in new folder `/helpers/getUserData.js` and then imported.

Also this function could be simplified:
```
const getUserData = () => isMobile ? `${browserName} ${osName} ${mobileModel}` : `${browserName} ${osName}`;
```

**Comment by radekxrandom** [comment]
Of course they could be placed in a new folder. Of course that function could be simplified.
